---
apiVersion: v1
kind: Pod
metadata:
       name: my-nginx
       labels:
               name: app
               version: v1
spec:
  containers:
  - name: nginx-test
    image: nginx
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
       name: my-httpd
       labels:
               name: app
               version: v2
spec:
  containers:
  - name: nginx-test
    image: httpd
    ports:
    - containerPort: 80
