apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
spec:
        replicas: 2
        selector:
                name: applogin
        template:        
          metadata:
            name: my-httpd
            labels:
                  name: applogin
          spec:
            containers:
            - name: nginx-test
              image: httpd
              ports:
              - containerPort: 80
