apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
        selector:
                        name: app
                        version: v2
        ports:
                - name: nginxport
                  port: 81
                  nodePort: 30081
        type: NodePort                  
                          
